/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./components/Icon.vue')['default']
    IndexChangeServerCard: typeof import('./components/IndexChangeServerCard.vue')['default']
    IndexDownload: typeof import('./components/IndexDownload.vue')['default']
    IndexInfo: typeof import('./components/IndexInfo.vue')['default']
    IndexInputCode: typeof import('./components/IndexInputCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
